name: safemanager
description: Offline credential manager for a single device.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3
  path: ^1.9.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
